name: Image áttöltése GHCR-re
on: 
  workflow_dispatch:

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout kód
        uses: actions/checkout@v4

      - name: Bejelentkezés a GHCR-be
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Image letöltése (Automatikus Tag kereséssel)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Listázzuk ki a release-eket, vegyük a legfrissebbet, és töltsük le a .tar fájlt
          gh release download --pattern "*.tar" --clobber

      - name: Ellenőrzés
        run: ls -lh *.tar

      - name: Image betöltése, címkézése és feltolása
        run: |
          # Mivel a fájlnevet pontosan nem fixáltuk, a *.tar-t töltjük be
          docker load -i *.tar
          
          # ID kinyerése
          IMAGE_ID=$(docker images -q | head -n 1)
          echo "Betöltött Image ID: $IMAGE_ID"
          
          # Feltolás a saját repódba
          docker tag $IMAGE_ID ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
